### ISSUE TITLE
Rename token env var to CARGO_FUND_GITHUB_API_TOKEN

### ISSUE THREAD

**Issue by smacintyre** [acfoltzer/cargo-fund#3]
## The issue

Other applications make use of the `GITHUB_API_TOKEN` variable. This makes it hard to have application specific with minimum required privileges for each app. 

## Proposed solution

Name space the environment variable that `cargo fund` used by prefixing it with `CARGO_FUND_` or something similar. So the environment variable will be called: `CARGO_FUND_GITHUB_API_TOKEN`.

## Prior Art

See `brew`'s [environment variables](https://docs.brew.sh/Manpage#environment). Specifically `HOMEBREW_GITHUB_API_TOKEN`

**Comment by smacintyre** [comment]
I should also add that `cargo fund` is a great idea for a tool! Thank you for making it.

**Comment by acfoltzer** [comment]
Hey, thank you so much for the kind words! This hadn't occurred to me, but is a great idea.
