### ISSUE TITLE
Increase timeout

### ISSUE THREAD

**Issue by repi** [acfoltzer/cargo-fund#4]
Awesome small tool and initiative!

When I ran it on our fairly large project with 510 dependencies the default 5 second timeout kept being triggered though, seems to take around 12 seconds for our query. 

There are projects with even more dependencies so how about increasing the default timeout to 30 sec?

**Comment by acfoltzer** [comment]
Thank you so much for the kind words! I'd accidentally left this low value in from when I was first prototyping; #6 sets the timeout to a minute. I'm really excited to know that it's now being run on projects large enough to need more headroom (and, you know, video games :heart_eyes_cat:)
