### ISSUE TITLE
Tag release for 0.2.0

### ISSUE THREAD

**Issue by wezm** [acfoltzer/cargo-fund#7]
Hello, this is a great idea, thanks for building it. I have created an [AUR package for `cargo-fund`](https://aur.archlinux.org/packages/cargo-fund/), which is built from tagged releases. I see that a 0.2.0 version has been released to crates.io but not tagged in git. Would it be possible to tag this version (and future versions) in git as well?

**Comment by acfoltzer** [comment]
Done; thank you for the reminder!
